###получения всех продуктов
GET http://localhost:8080/products
Accept: application/json

###получения продукта по id
GET http://localhost:8080/products/666
Accept: application/json

###получения продукта по имени начинающемуся с...
GET http://localhost:8080/products/findByNameStartsWith/Ручка
Accept: application/json

###получения продукта по производителю
GET http://localhost:8080/products/findByManufacturer/Apecs
Accept: application/json

###добавление нового продукта
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Волшебный ящик, Grey",
  "manufacturer": "PavelCompany",
  "amount": "шт",
  "priceBYN": "300.99"
}

###удаление продукта по id
DELETE http://localhost:8080/products/801
Content-Type: application/json